server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
 
 
zuul:
#  ignored-services: microservicecloud-dept  #隐藏真实的服务名称
  prefix: /mao    #路径加前缀
  ignored-services: "*"   #隐藏所有真实的服务名称
  routes:
    mydept.serviceId: microservicecloud-dept   #真是服务 eureka的服务名称
    mydept.path: /mydept/** #代理名称  对外暴露的名称
 
info:
  app.name: mao-microcloud
  company.name: www.mao.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

spring:
    profiles:
        active:
        - dev

---
spring:
    profiles: dev    #开发环境
    application:
        name: microservicecloud-config-mao-dev

---
spring:
    profiles: test    #测试环境
    application:
        name: microservicecloud-config-mao-test
# 请保存为UTF-8格式